[package]
name = "fuzi"
version = "0.0.0"
edition = "2024"
licence = "MIT"
description = """
HTTP/3 based Web application framework
"""
readme = "README.md"
documentation = "https://docs.rs/fuzi"
repository = "https://github.com/nakaryo716/fuzi"

[dependencies]
